spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/briefing
#    username: postgres
#    password: postgres
    username: ${aws.db.username}
    password: ${aws.db.password}
    url: ${aws.db.url}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        #        show_sql: true
        #        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  config:
    activate:
      on-profile: default
  data:
    redis:
      host: briefing-redis-cluster.0ot2cs.ng.0001.apn2.cache.amazonaws.com
      port: 6379
jwt:
  header: Authorization
  # dev server
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
#  secret : ${JWT_SECRET}
  authorities-key: authoritiesKey
  access-token-validity-in-seconds: 1210000000 # 30 m
  refresh-token-validity-in-seconds: 1210000000 # 14 d

openai:
  token: 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
  url:
    chat: https://api.openai.com/v1/chat/completions

springdoc:
  swagger-ui:
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  cache:
    disabled: true
  use-fqn: true
