spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/briefing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: validate
  config:
    activate:
      on-profile: default

openai:
  token: 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
  url:
    chat: https://api.openai.com/v1/chat/completions
