spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/briefing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      format_sql: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  config:
    activate:
      on-profile: default

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

scrap:
  url:
    정치: https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=100
    경제: https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=101
    사회: https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=102
    생활_문화: https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=103
    IT_과학: https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=105
    세계: https://news.naver.com/main/main.naver?mode=LSD&mid=shm&sid1=104

openai:
  token: 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
  url:
    chat: https://api.openai.com/v1/chat/completions
