insert into briefing (type, rank, title, subtitle, content, created_at, updated_at)
VALUES ('KOREA', 1, '제목1', '부제목1', '내용1', current_timestamp, current_timestamp),
       ('KOREA', 2, '제목2', '부제목2', '내용2', current_timestamp, current_timestamp),
       ('KOREA', 3, '제목3', '부제목3', '내용3', current_timestamp, current_timestamp),
       ('KOREA', 4, '제목4', '부제목4', '내용4', current_timestamp, current_timestamp),
       ('KOREA', 5, '제목5', '부제목5', '내용5', current_timestamp, current_timestamp),
       ('KOREA', 6, '제목6', '부제목6', '내용6', current_timestamp, current_timestamp),
       ('KOREA', 7, '제목7', '부제목7', '내용7', current_timestamp, current_timestamp),
       ('KOREA', 8, '제목8', '부제목8', '내용8', current_timestamp, current_timestamp),
       ('KOREA', 9, '제목9', '부제목9', '내용9', current_timestamp, current_timestamp),
       ('KOREA', 10, '제목10', '부제목10', '내용10', current_timestamp, current_timestamp),
       ('KOREA', 11, '제목11', '부제목11', '내용11', current_timestamp, current_timestamp),
       ('KOREA', 12, '제목12', '부제목12', '내용12', current_timestamp, current_timestamp),
       ('KOREA', 13, '제목13', '부제목13', '내용13', current_timestamp, current_timestamp),
       ('KOREA', 14, '제목14', '부제목14', '내용14', current_timestamp, current_timestamp),
       ('KOREA', 15, '제목15', '부제목15', '내용15', current_timestamp, current_timestamp),
       ('GLOBAL', 1, 'title1', 'subtitle1', 'content1', current_timestamp, current_timestamp),
       ('GLOBAL', 2, 'title2', 'subtitle2', 'content2', current_timestamp, current_timestamp),
       ('GLOBAL', 3, 'title3', 'subtitle3', 'content3', current_timestamp, current_timestamp),
       ('GLOBAL', 4, 'title4', 'subtitle4', 'content4', current_timestamp, current_timestamp),
       ('GLOBAL', 5, 'title5', 'subtitle5', 'content5', current_timestamp, current_timestamp),
       ('GLOBAL', 6, 'title6', 'subtitle6', 'content6', current_timestamp, current_timestamp),
       ('GLOBAL', 7, 'title7', 'subtitle7', 'content7', current_timestamp, current_timestamp),
       ('GLOBAL', 8, 'title8', 'subtitle8', 'content8', current_timestamp, current_timestamp),
       ('GLOBAL', 9, 'title9', 'subtitle9', 'content9', current_timestamp, current_timestamp),
       ('GLOBAL', 10, 'title10', 'subtitle10', 'content10', current_timestamp, current_timestamp),
       ('GLOBAL', 11, 'title11', 'subtitle11', 'content11', current_timestamp, current_timestamp),
       ('GLOBAL', 12, 'title12', 'subtitle12', 'content12', current_timestamp, current_timestamp),
       ('GLOBAL', 13, 'title13', 'subtitle13', 'content13', current_timestamp, current_timestamp),
       ('GLOBAL', 14, 'title14', 'subtitle14', 'content14', current_timestamp, current_timestamp),
       ('GLOBAL', 15, 'title15', 'subtitle15', 'content15', current_timestamp, current_timestamp);

insert into article (press, title, url, created_at, updated_at)
VALUES ('press1', 'title1', 'https://url1.com', current_timestamp, current_timestamp),
       ('press2', 'title2', 'https://url2.com', current_timestamp, current_timestamp),
       ('press3', 'title3', 'https://url3.com', current_timestamp, current_timestamp),
       ('press4', 'title4', 'https://url4.com', current_timestamp, current_timestamp),
       ('press5', 'title5', 'https://url5.com', current_timestamp, current_timestamp),
       ('press6', 'title6', 'https://url6.com', current_timestamp, current_timestamp),
       ('press7', 'title7', 'https://url7.com', current_timestamp, current_timestamp),
       ('press8', 'title8', 'https://url8.com', current_timestamp, current_timestamp),
       ('press9', 'title9', 'https://url9.com', current_timestamp, current_timestamp),
       ('press10', 'title10', 'https://url10.com', current_timestamp, current_timestamp),
       ('press11', 'title11', 'https://url11.com', current_timestamp, current_timestamp),
       ('press12', 'title12', 'https://url12.com', current_timestamp, current_timestamp),
       ('press13', 'title13', 'https://url13.com', current_timestamp, current_timestamp),
       ('press14', 'title14', 'https://url14.com', current_timestamp, current_timestamp),
       ('press15', 'title15', 'https://url15.com', current_timestamp, current_timestamp),
       ('press16', 'title16', 'https://url16.com', current_timestamp, current_timestamp),
       ('press17', 'title17', 'https://url17.com', current_timestamp, current_timestamp),
       ('press18', 'title18', 'https://url18.com', current_timestamp, current_timestamp),
       ('press19', 'title19', 'https://url19.com', current_timestamp, current_timestamp),
       ('press20', 'title20', 'https://url20.com', current_timestamp, current_timestamp),
       ('press21', 'title21', 'https://url21.com', current_timestamp, current_timestamp),
       ('press22', 'title22', 'https://url22.com', current_timestamp, current_timestamp),
       ('press23', 'title23', 'https://url23.com', current_timestamp, current_timestamp),
       ('press24', 'title24', 'https://url24.com', current_timestamp, current_timestamp),
       ('press25', 'title25', 'https://url25.com', current_timestamp, current_timestamp),
       ('press26', 'title26', 'https://url26.com', current_timestamp, current_timestamp),
       ('press27', 'title27', 'https://url27.com', current_timestamp, current_timestamp),
       ('press28', 'title28', 'https://url28.com', current_timestamp, current_timestamp),
       ('press29', 'title29', 'https://url29.com', current_timestamp, current_timestamp),
       ('press30', 'title30', 'https://url30.com', current_timestamp, current_timestamp),
       ('press31', 'title31', 'https://url31.com', current_timestamp, current_timestamp),
       ('press32', 'title32', 'https://url32.com', current_timestamp, current_timestamp),
       ('press33', 'title33', 'https://url33.com', current_timestamp, current_timestamp),
       ('press34', 'title34', 'https://url34.com', current_timestamp, current_timestamp),
       ('press35', 'title35', 'https://url35.com', current_timestamp, current_timestamp),
       ('press36', 'title36', 'https://url36.com', current_timestamp, current_timestamp),
       ('press37', 'title37', 'https://url37.com', current_timestamp, current_timestamp),
       ('press38', 'title38', 'https://url38.com', current_timestamp, current_timestamp),
       ('press39', 'title39', 'https://url39.com', current_timestamp, current_timestamp),
       ('press40', 'title40', 'https://url40.com', current_timestamp, current_timestamp),
       ('press41', 'title41', 'https://url41.com', current_timestamp, current_timestamp),
       ('press42', 'title42', 'https://url42.com', current_timestamp, current_timestamp),
       ('press43', 'title43', 'https://url43.com', current_timestamp, current_timestamp),
       ('press44', 'title44', 'https://url44.com', current_timestamp, current_timestamp),
       ('press45', 'title45', 'https://url45.com', current_timestamp, current_timestamp),
       ('press46', 'title46', 'https://url46.com', current_timestamp, current_timestamp),
       ('press47', 'title47', 'https://url47.com', current_timestamp, current_timestamp),
       ('press48', 'title48', 'https://url48.com', current_timestamp, current_timestamp),
       ('press49', 'title49', 'https://url49.com', current_timestamp, current_timestamp),
       ('press50', 'title50', 'https://url50.com', current_timestamp, current_timestamp),
       ('press51', 'title51', 'https://url51.com', current_timestamp, current_timestamp),
       ('press52', 'title52', 'https://url52.com', current_timestamp, current_timestamp),
       ('press53', 'title53', 'https://url53.com', current_timestamp, current_timestamp),
       ('press54', 'title54', 'https://url54.com', current_timestamp, current_timestamp),
       ('press55', 'title55', 'https://url55.com', current_timestamp, current_timestamp),
       ('press56', 'title56', 'https://url56.com', current_timestamp, current_timestamp),
       ('press57', 'title57', 'https://url57.com', current_timestamp, current_timestamp),
       ('press58', 'title58', 'https://url58.com', current_timestamp, current_timestamp),
       ('press59', 'title59', 'https://url59.com', current_timestamp, current_timestamp),
       ('press60', 'title60', 'https://url60.com', current_timestamp, current_timestamp),
       ('press61', 'title61', 'https://url61.com', current_timestamp, current_timestamp),
       ('press62', 'title62', 'https://url62.com', current_timestamp, current_timestamp),
       ('press63', 'title63', 'https://url63.com', current_timestamp, current_timestamp),
       ('press64', 'title64', 'https://url64.com', current_timestamp, current_timestamp),
       ('press65', 'title65', 'https://url65.com', current_timestamp, current_timestamp),
       ('press66', 'title66', 'https://url66.com', current_timestamp, current_timestamp),
       ('press67', 'title67', 'https://url67.com', current_timestamp, current_timestamp),
       ('press68', 'title68', 'https://url68.com', current_timestamp, current_timestamp),
       ('press69', 'title69', 'https://url69.com', current_timestamp, current_timestamp),
       ('press70', 'title70', 'https://url70.com', current_timestamp, current_timestamp),
       ('press71', 'title71', 'https://url71.com', current_timestamp, current_timestamp),
       ('press72', 'title72', 'https://url72.com', current_timestamp, current_timestamp),
       ('press73', 'title73', 'https://url73.com', current_timestamp, current_timestamp),
       ('press74', 'title74', 'https://url74.com', current_timestamp, current_timestamp),
       ('press75', 'title75', 'https://url75.com', current_timestamp, current_timestamp),
       ('press76', 'title76', 'https://url76.com', current_timestamp, current_timestamp),
       ('press77', 'title77', 'https://url77.com', current_timestamp, current_timestamp),
       ('press78', 'title78', 'https://url78.com', current_timestamp, current_timestamp),
       ('press79', 'title79', 'https://url79.com', current_timestamp, current_timestamp),
       ('press80', 'title80', 'https://url80.com', current_timestamp, current_timestamp),
       ('press81', 'title81', 'https://url81.com', current_timestamp, current_timestamp),
       ('press82', 'title82', 'https://url82.com', current_timestamp, current_timestamp),
       ('press83', 'title83', 'https://url83.com', current_timestamp, current_timestamp),
       ('press84', 'title84', 'https://url84.com', current_timestamp, current_timestamp),
       ('press85', 'title85', 'https://url85.com', current_timestamp, current_timestamp),
       ('press86', 'title86', 'https://url86.com', current_timestamp, current_timestamp),
       ('press87', 'title87', 'https://url87.com', current_timestamp, current_timestamp),
       ('press88', 'title88', 'https://url88.com', current_timestamp, current_timestamp),
       ('press89', 'title89', 'https://url89.com', current_timestamp, current_timestamp),
       ('press90', 'title90', 'https://url90.com', current_timestamp, current_timestamp);

insert into briefing_article (briefing_id, article_id, created_at, updated_at)
VALUES (1, 1, current_timestamp, current_timestamp),
       (1, 2, current_timestamp, current_timestamp),
       (1, 3, current_timestamp, current_timestamp),
       (2, 4, current_timestamp, current_timestamp),
       (2, 5, current_timestamp, current_timestamp),
       (2, 6, current_timestamp, current_timestamp),
       (3, 7, current_timestamp, current_timestamp),
       (3, 8, current_timestamp, current_timestamp),
       (3, 9, current_timestamp, current_timestamp),
       (4, 10, current_timestamp, current_timestamp),
       (4, 11, current_timestamp, current_timestamp),
       (4, 12, current_timestamp, current_timestamp),
       (5, 13, current_timestamp, current_timestamp),
       (5, 14, current_timestamp, current_timestamp),
       (5, 15, current_timestamp, current_timestamp),
       (6, 16, current_timestamp, current_timestamp),
       (6, 17, current_timestamp, current_timestamp),
       (6, 18, current_timestamp, current_timestamp),
       (7, 19, current_timestamp, current_timestamp),
       (7, 20, current_timestamp, current_timestamp),
       (7, 21, current_timestamp, current_timestamp),
       (8, 22, current_timestamp, current_timestamp),
       (8, 23, current_timestamp, current_timestamp),
       (8, 24, current_timestamp, current_timestamp),
       (9, 25, current_timestamp, current_timestamp),
       (9, 26, current_timestamp, current_timestamp),
       (9, 27, current_timestamp, current_timestamp),
       (10, 28, current_timestamp, current_timestamp),
       (10, 29, current_timestamp, current_timestamp),
       (10, 30, current_timestamp, current_timestamp),
       (11, 31, current_timestamp, current_timestamp),
       (11, 32, current_timestamp, current_timestamp),
       (11, 33, current_timestamp, current_timestamp),
       (12, 34, current_timestamp, current_timestamp),
       (12, 35, current_timestamp, current_timestamp),
       (12, 36, current_timestamp, current_timestamp),
       (13, 37, current_timestamp, current_timestamp),
       (13, 38, current_timestamp, current_timestamp),
       (13, 39, current_timestamp, current_timestamp),
       (14, 40, current_timestamp, current_timestamp),
       (14, 41, current_timestamp, current_timestamp),
       (14, 42, current_timestamp, current_timestamp),
       (15, 43, current_timestamp, current_timestamp),
       (15, 44, current_timestamp, current_timestamp),
       (15, 45, current_timestamp, current_timestamp),
       (16, 46, current_timestamp, current_timestamp),
       (16, 47, current_timestamp, current_timestamp),
       (16, 48, current_timestamp, current_timestamp),
       (17, 49, current_timestamp, current_timestamp),
       (17, 50, current_timestamp, current_timestamp),
       (17, 51, current_timestamp, current_timestamp),
       (18, 52, current_timestamp, current_timestamp),
       (18, 53, current_timestamp, current_timestamp),
       (18, 54, current_timestamp, current_timestamp),
       (19, 55, current_timestamp, current_timestamp),
       (19, 56, current_timestamp, current_timestamp),
       (19, 57, current_timestamp, current_timestamp),
       (20, 58, current_timestamp, current_timestamp),
       (20, 59, current_timestamp, current_timestamp),
       (20, 60, current_timestamp, current_timestamp),
       (21, 61, current_timestamp, current_timestamp),
       (21, 62, current_timestamp, current_timestamp),
       (21, 63, current_timestamp, current_timestamp),
       (22, 64, current_timestamp, current_timestamp),
       (22, 65, current_timestamp, current_timestamp),
       (22, 66, current_timestamp, current_timestamp),
       (23, 67, current_timestamp, current_timestamp),
       (23, 68, current_timestamp, current_timestamp),
       (23, 69, current_timestamp, current_timestamp),
       (24, 70, current_timestamp, current_timestamp),
       (24, 71, current_timestamp, current_timestamp),
       (24, 72, current_timestamp, current_timestamp),
       (25, 73, current_timestamp, current_timestamp),
       (25, 74, current_timestamp, current_timestamp),
       (25, 75, current_timestamp, current_timestamp),
       (26, 76, current_timestamp, current_timestamp),
       (26, 77, current_timestamp, current_timestamp),
       (26, 78, current_timestamp, current_timestamp),
       (27, 79, current_timestamp, current_timestamp),
       (27, 80, current_timestamp, current_timestamp),
       (27, 81, current_timestamp, current_timestamp),
       (28, 82, current_timestamp, current_timestamp),
       (28, 83, current_timestamp, current_timestamp),
       (28, 84, current_timestamp, current_timestamp),
       (29, 85, current_timestamp, current_timestamp),
       (29, 86, current_timestamp, current_timestamp),
       (29, 87, current_timestamp, current_timestamp),
       (30, 88, current_timestamp, current_timestamp),
       (30, 89, current_timestamp, current_timestamp),
       (30, 90, current_timestamp, current_timestamp);

insert into chatting (title, created_at, updated_at)
VALUES ('title1', current_timestamp, current_timestamp),
       ('title2', current_timestamp, current_timestamp),
       ('title3', current_timestamp, current_timestamp),
       ('title4', current_timestamp, current_timestamp),
       ('title5', current_timestamp, current_timestamp),
       ('title6', current_timestamp, current_timestamp),
       ('title7', current_timestamp, current_timestamp),
       ('title8', current_timestamp, current_timestamp),
       ('title9', current_timestamp, current_timestamp),
       ('title10', current_timestamp, current_timestamp);

insert into message (chatting_id, role, content, created_at)
values (1, 'SYSTEM', 'system content', current_timestamp),
       (1, 'ASSISTANT', 'assiatant content', current_timestamp),
       (1, 'USER', 'user content', current_timestamp),
       (2, 'SYSTEM', 'system content', current_timestamp),
       (2, 'ASSISTANT', 'assiatant content', current_timestamp),
       (2, 'USER', 'user content', current_timestamp),
       (3, 'SYSTEM', 'system content', current_timestamp),
       (3, 'ASSISTANT', 'assiatant content', current_timestamp),
       (3, 'USER', 'user content', current_timestamp),
       (4, 'SYSTEM', 'system content', current_timestamp),
       (4, 'ASSISTANT', 'assiatant content', current_timestamp),
       (4, 'USER', 'user content', current_timestamp),
       (5, 'SYSTEM', 'system content', current_timestamp),
       (5, 'ASSISTANT', 'assiatant content', current_timestamp),
       (5, 'USER', 'user content', current_timestamp),
       (6, 'SYSTEM', 'system content', current_timestamp),
       (6, 'ASSISTANT', 'assiatant content', current_timestamp),
       (6, 'USER', 'user content', current_timestamp),
       (7, 'SYSTEM', 'system content', current_timestamp),
       (7, 'ASSISTANT', 'assiatant content', current_timestamp),
       (7, 'USER', 'user content', current_timestamp),
       (8, 'SYSTEM', 'system content', current_timestamp),
       (8, 'ASSISTANT', 'assiatant content', current_timestamp),
       (8, 'USER', 'user content', current_timestamp),
       (9, 'SYSTEM', 'system content', current_timestamp),
       (9, 'ASSISTANT', 'assiatant content', current_timestamp),
       (9, 'USER', 'user content', current_timestamp),
       (10, 'SYSTEM', 'system content', current_timestamp),
       (10, 'ASSISTANT', 'assiatant content', current_timestamp),
       (10, 'USER', 'user content', current_timestamp);
