spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    properties:
      hibernate:
        ddl-auto: update
        show_sql: true
        format_sql: true
        use_sql_comments: true